# https://taskfile.dev

version: '3'

tasks:

  commit:windows:
    dir: scripts
    platforms:
      - windows
    cmds:
      - git add .
      - git commit -m 'Update to Webview {{.VERSION}}'
    vars:
      VERSION:
        sh: powershell cat latest_version.txt

  commit:unix:
    dir: scripts
    platforms:
      - darwin
      - linux
    cmds:
      - git add .
      - git commit -m 'Update to Webview {{.VERSION}}'
    vars:
      VERSION:
        sh: cat latest_version.txt

  commit:
    cmds:
      - task: commit:windows
      - task: commit:unix

  gofmt:
    dir: pkg/webview2
    cmds:
      - go fmt

  test:
    cmds:
      - go test ./...

  update:
    dir: scripts
    cmds:
      - go run update_version_mapping.go
      - task: gofmt
      - go fmt update_version_mapping.go
      - task: test
      - task: commit

  update:forced:
    dir: scripts
    cmds:
      - go run update_version_mapping.go -forced
      - task: gofmt
      - go fmt update_version_mapping.go
      - task: test
      - task: commit
